dist: bionic
language: ruby

rvm:
  - 2.5
  - 2.6
  - 2.7

script: bundle exec cucumber

deploy:
  provider: rubygems
  api_key:
    secure: F3OlvNMbpmfeqfhpHVyvlZAfj6U17QblCrHG8uyeX5seGaKx7ilScthzcS48BG7Vg2faQmZYnCLf/fpnVCQhpT9e/HXqVhyM7mlSGwiToVjAKFt2F4dfIdR+n3XIzUFch0oaXxIs7BrBRUrum8E0QyysAC1yWx1tMvNhQ2bKvuV+z4G4hlpr+eDvRBFizDF+4mqdUtJCI80VsAse63YAO3Y9cF8MP6UikWsn1eIPjcwsRZd4jKRiuiMC5wtPLZtoq+1IK9TCLqnxLKuC6R/jDTWwUcisfTeRPDYfSgFADwqj9jm6vB37Uli3wOM6oo/5Qkj6p9X0PUbE9jdpepus7YuxvRL5Zn+QgXCkw/r59aWw1QCrZdb84J09zttBqKyU8jUufn8le23RuLhTIU40pJdCn3/dGnGHeHY5ZdHZYrGWcAMzE88gWcjBAiw8eXEglIf1VjfbIntgGeEdB3iyom3SmKG1koK5Tye9tfMxW0Yvewp7EJDlKajtqTEnVnq2+hAOtj/a18ONrm4PJzQ/6dR22rd4Bjaapt3CEKiuFychHeVJFlzdzKL8WGJe+dQyzKmZALqYKeT6K97FCz1pL8ZhSpEnjr8AeW+Je8N3ExgJwTH16KanAJhUYmRMdYRIsrvlz060LPzihGQI5VrsUI8cpFBSh5DfDbuUro4evZ0=
  on:
    tags: true
    repo: mdsol/kender
    condition: $TRAVIS_RUBY_VERSION == 2.7
