dist: bionic
language: ruby

rvm:
  - 2.5
  - 2.6
  - 2.7

script: bundle exec cucumber

deploy:
  provider: rubygems
  api_key:
    secure: IILrGywDTwAJskfikzs4Wx16e/Mcl+fd6EoFOXp57/vI9HONN5bjvSnO7ixluVJzMusOMyihIfnzxL9AuegTeBqgup6W944c3/9xHZec6t1JJRe1ELZP5SXPUwWMGdDmyWfBu7tqacTicGUrZ1/3quoOihJ0DcNEMUYzqLJdnXk=
  on:
    tags: true
    repo: mdsol/kender
    condition: $TRAVIS_RUBY_VERSION == 2.7
